### ISSUE TITLE
Org Creation Fails with ACCESS_DENIED

### ISSUE THREAD

**Issue by shafi-codez** [forcedotcom/sfdx-simple#22]
Automation was working previously now seems to be broken

{"message":"You do not have access to the [ScratchOrgInfo] object","status":1,"name":"ACCESS_DENIED"}

**Comment by wadewegner** [comment]
Please ensure you're running this against an org setup as a Dev Hub.

https://developer.salesforce.com/docs/atlas.en-us.sfdx_setup.meta/sfdx_setup/sfdx_setup_enable_devhub.htm
