### ISSUE TITLE
ERROR running force:org:create:  You do not have access to the [ScratchOrgInfo] object

### ISSUE THREAD

**Issue by mdevalla** [forcedotcom/sfdx-simple#23]
I keep getting : ERROR running force:org:create:  You do not have access to the [ScratchOrgInfo] object.

**Comment by tempflip** [comment]
@mdevalla probably you need to connect your SFDX to a developer hub.

```
$ sfdx force:org:list
=== Orgs
     ALIAS         USERNAME                ORG ID              CONNECTED STATUS
───  ────────────  ──────────────────────  ──────────────────  ────────────────

(D)  DevHub        peter@XXXX   XXXXX  Connected
```

**Comment by skyrpex** [comment]
I got the same error, and I already connected SFDX to my account.

Maybe my account doesn't have the rights to create a new ORG?

**Comment by patrickyong** [comment]
I have the same issue as well

**Comment by sisodiabhumca** [comment]
I am also getting same error - 

sfdx force:org:list
=== Orgs
     ALIAS   USERNAME                 ORG ID              CONNECTED STATUS
───  ──────  ───────────────────────  ──────────────────  ────────────────
(D)  Devhub  xxxxxxx  00D36000000umZuEAI  Connected

**Comment by divanoff** [comment]
Same error, devhub org connected. Also, tried creating another trial org and then deleting the first one. That didn't solve the problem. I've tried several different solutions so far and none of them worked. It would be interesting to find out what causes this. Thanks

**Comment by tempflip** [comment]
hmm, make sure dev hub is enabled (i think only for paid org):

https://developer.salesforce.com/docs/atlas.en-us.sfdx_setup.meta/sfdx_setup/sfdx_setup_enable_devhub.htm

or here you can get an enabled one out-of-the-box for free:

https://developer.salesforce.com/promotions/orgs/dx-signup

**Comment by divanoff** [comment]
Yep, brand new trial org. Dev Hub is active by default on new orgs and you can't turn it off. Tried everything, no go

**Comment by divanoff** [comment]
@tempflip The second link makes all the difference! I didn't realize that a regular trial org doesn't support SFDX. Kind of a subtle but important detail :) Thank you!

**Comment by vensant** [comment]
@tempflip  your second link worked like a charm! Thank you!

**Comment by Jasonlhy** [comment]
When i connect to Sandbox with winter 18 release, same problem happened. It seems that DevHub is only supported in production environment

**Comment by choose0or7** [comment]
@tempflip Thanks for your answer. Developer org cannot enable Dev Hub.

**Comment by LeandroHotmail** [comment]
Dear all, it's possible to use a temporally DX Org to connect with your Dev org:

C:\sfdx-simple>sfdx force:org:list
Orgs     ALIAS          USERNAME                         ORG ID              CONNECTED STATUS
SF-Hotmail     xxxxxx@hotmail.com     00D61000000ZDe8EAG  Connected
(D)  SF-Hotmail-DX  xxxxxx@hotmail.com.dx  00D1I000001dMImUAM  Connected

ALIAS  SCRATCH ORG NAME  USERNAME                          ORG ID              EXPIRATION DATE
(U)         SF-Hotmail        test-o9cm1m5utbnh@sf-hotmail.net  00D56000000CtEcEAK  2017-11-14

SF-Hotmail-DX  xxxxxx@hotmail.com.dx it is a new temporally Dev to use for some DX Labs, but remember it´s a temporally opportunity.

**Comment by gnanadeeptu** [comment]
Hi All, 

Instead of using just "sfdx force:org:list" use "sfdx force:org:list --all" to see ALIAS SCRATCH ORG's as well. Without -all argument that is not displayed.

**Comment by chetan-kamble** [comment]
thanks tempflip......

Create new 30 days DX org
https://developer.salesforce.com/promotions/orgs/dx-signup

Second link is useful

**Comment by wadewegner** [comment]
Thanks all!

**Comment by venkatasykam** [comment]
@tempflip 

an even second link is also not working for me.

**Comment by daveb-501commons** [comment]
I was getting the same error

`sfdx force:org:create -f orgs/dev.json -n --durationdays 7 -a [alias]

Error: You do not have access to the [ScratchOrgInfo] object`

**Resolution:**

'sfdx force:auth:web:login -d -a DevHub'

**Issue Explained:**

https://developer.salesforce.com/docs/atlas.en-us.sfdx_cli_reference.meta/sfdx_cli_reference/cli_reference_force_auth.htm#cli_reference_force_auth
-d | --setdefaultdevhubusername
Optional
Sets the authenticated org as the default Dev Hub org for scratch org creation.
Type: flag

The issue was my defaultdevhubusername was pointing to a different org.  When you call sfdx force:auth:web:login w/ the -d flag it will also set the defaultdevhubusername that is used for scratch org auth.

Alternatively if you already have the user setup in your keychain you can just set the defaultdevhubusername directly without creating a new key chain alias.
 

'sfdx force:config:set defaultdevhubusername=[username]'

**Comment by datatalking** [comment]
I am getting this error as well.

Even after completeing daveb-501commons 04/23 update.
'ERROR:  You do not have access to the [ScratchOrgInfo] object'

The error remains.

**Comment by shailendra121** [comment]
https://success.salesforce.com/ideaView?id=0873A000000PZS6QAO

**Comment by dhaniksahni** [comment]
I have enabled DevHub and it worked.

**Comment by manoj10029** [comment]
> 
> 
> hmm, make sure dev hub is enabled (i think only for paid org):
> 
> https://developer.salesforce.com/docs/atlas.en-us.sfdx_setup.meta/sfdx_setup/sfdx_setup_enable_devhub.htm
> 
> or here you can get an enabled one out-of-the-box for free:
> 
> https://developer.salesforce.com/promotions/orgs/dx-signup

I have enabled DevHub, And it work for me.
Thank you

**Comment by Mahakb** [comment]
I had to enable the devhub in my pre-release spring 19 org. As without enabling devhub, I was not able to create scratch org as I didnt had the access to the same.

**Comment by GodLin1994** [comment]
you can tru to  enable Dev Hub in set up

**Comment by dkochheiser** [comment]
@Mahakb Your solution worked for me, thanks! Just to add on for the newbies, use the Quick Search bar after you're logged in and use the first slider to enable the dev hub.

**Comment by deepak3c** [comment]
1) Use Windows Powershell, its recognizes many commands.

2) Login to web into your SalesForce account. Go to Setup. Search Dev Hub. Enable Dev Hub. Save the settings.

Then come back to windows powershell enter
sfdx force:org:create -s -f config/project-scratch-def.json -a dreamhouse-org

And your done!

I spend lot of time on this issue, and this worked for me using above steps.

**Comment by mansoir** [comment]
To enable Dev Hub in an org:

Log in as System Administrator to your Developer Edition, trial, or production org (if you’re a customer), or your business org (if you’re an ISV).
From Setup, enter Dev Hub in the Quick Find box and select Dev Hub.
If you don't see Dev Hub in the Setup menu, make sure your org is one of the supported editions.

To enable Dev Hub, click Enable.
After you enable Dev Hub, you can’t disa

**Comment by olympikesoft** [comment]
Go to **yourlinkacesstrailhead**.force.com/lightning/setup/DevHub/home
And after that enable DEV HUB.
Paste again the command on VSCode and should be working now.
:)

**Comment by pcon** [comment]
You will also get this issue if you are logged into an org and do not have the permissions listed in the [Add Users](https://developer.salesforce.com/docs/atlas.en-us.sfdx_setup.meta/sfdx_setup/sfdx_setup_add_users.htm) documentation

**Comment by zachelrath** [comment]
@pcon Thank you! Your answer is exactly what i needed. Somehow the Permission Set assigned to some of my team members had access to Active Scratch Org object, but did _not_ have access to the Scratch Org Info object or Namespace Registry. Adding that fixed it.

**Comment by bvrulez** [comment]
I get the same error, when trying to create a second scratch org on a second computer after doing it yesterday with the first computer successfully. Should I be able to work from different computers with the same devHub account?

**Comment by glalit54** [comment]
Hi All,

If you are facing issue creating scratch org from your VsCode  then please make sure that Dev hub is enabled of your default org  : 
Setup --> search for Dev Hub in quick searchbox --> enable Dev hub

Please let me know if it helps.

Regrards,
Lalit

**Comment by meghana0310** [comment]
Hi
Dev Hub enabled. Still same error. I am trying to install LWC App from GITHUB

**Comment by kamran-jabbar** [comment]
> hmm, make sure dev hub is enabled (i think only for paid org):
> 
> https://developer.salesforce.com/docs/atlas.en-us.sfdx_setup.meta/sfdx_setup/sfdx_setup_enable_devhub.htm
> 
> or here you can get an enabled one out-of-the-box for free:
> 
> https://developer.salesforce.com/promotions/orgs/dx-signup

This worked for me, thank you.

**Comment by meghana0310** [comment]
Resolved . Its because of Access issues on Object
