### ISSUE TITLE
force:apex:test:report freezed

### ISSUE THREAD

**Issue by fracarma** [forcedotcom/sfdx-simple#27]
Hello,

I know that this repository is just an example, but I didn't find a better place to post about this issue.
I connected with a Dev Edition and I run my test with the command
```
sfdx force:apex:test:run
```
The CLI returns the message `Run "sfdx force:apex:test:report -i 7072400005bqbbz" to retrieve test results.`
On the SF page Apex Test Execution I can see my test run and finish. But if I run the CLI command, the process basically freezes.
I tried to run the tests synchronously:

```
sfdx force:apex:test:run --resultformat human
```
The result is the same, the CLI freezes but I can see the tests run on the SF instance.

Thanks!

**Comment by ruthemmanuelle** [comment]
You'll reach a wider audience by reporting this issue in the Salesforce DX Beta group in the Success Community: https://success.salesforce.com/_ui/core/chatter/groups/GroupProfilePage?g=0F93A000000HTp1
