### ISSUE TITLE
Unable to do Salesforce DX CLI login for sandbox ( Authorization)

### ISSUE THREAD

**Issue by Azmathulla** [forcedotcom/sfdx-simple#29]
I have a doubt while I'm working on salesforce DX.

May I know if I can login to salesforce sandbox through visual studio code salesforce DX CLI?

I'm unable to do it, where would I get client id for it and I don't see enable Dev hub option inside org set up.

Is it because it works only on scratch org/Dev hub orgs and not on sandoxes ?

I just wanted my sandox data on vs code screen so that I start working with existing code . I have configured DX extension as well.

Kindly help.

**Comment by ruthemmanuelle** [comment]
See the "Help for auth:web:login" section of https://developer.salesforce.com/docs/atlas.en-us.sfdx_cli_reference.meta/sfdx_cli_reference/cli_reference_force_auth.htm#cli_reference_web_login for information on using the Salesforce CLI to log in to sandbox orgs. This functionality isn't currently available as a VS Code command, but you can run `sfdx force:auth:web:login -r https://test.salesforce.com` from a terminal.

You can't use a sandbox as your Dev Hub. For information about setting up your production org as a Dev Hub, see the Salesforce DX Setup Guide: https://developer.salesforce.com/docs/atlas.en-us.sfdx_setup.meta/sfdx_setup/sfdx_setup_enable_devhub.htm

Before you can work with the features that are in your sandbox you'll need to set up a Salesforce DX project: https://developer.salesforce.com/docs/atlas.en-us.sfdx_dev.meta/sfdx_dev/sfdx_dev_ws_create_from_existing.htm

Here's some Trailhead content to help you get started with Salesforce DX: https://trailhead.salesforce.com/en/trails/sfdx_get_started
