### ISSUE TITLE
 ts_types_1.definiteEntriesOf is not a function.

### ISSUE THREAD

**Issue by sunil114sharma** [forcedotcom/sfdx-simple#41]
Whenever I am going to create a new scratch org, I got this error.

![image](https://user-images.githubusercontent.com/28707459/50276481-0f38c780-0468-11e9-9f70-b221a5e088ff.png)

Error : 
![image](https://user-images.githubusercontent.com/28707459/50276525-2c6d9600-0468-11e9-8c91-cdf13186066f.png)

**Comment by rbergman** [comment]
Did you install the cli from an installer or npm?

**Comment by donaldrivard** [comment]
What does your project-scratch-def.json look like?

**Comment by rbergman** [comment]
Also, can you re-run the command with the `--dev-debug` flag and post the output?

**Comment by donaldrivard** [comment]
What are you using as your devhub?

**Comment by donaldrivard** [comment]
You should be using either a true production instance or a Developer Devhub instance. You can get a 30 day trail developer devhub instance here: https://developer.salesforce.com/promotions/orgs/dx-signup

**Comment by sunil114sharma** [comment]
yes.
i am using developer org.

**Comment by rbergman** [comment]
Out of curiosity you can try this: `sfdx plugins:install salesforcedx`

If that doesn't help I'd suggest uninstalling it again right away to prevent confusion down the road, like so: `sfdx plugins:uninstall salesforcedx`

**Comment by sunil114sharma** [comment]
Hi All,
Thanks for the fast response.
I re-install these application in my window.
Node.js
Git CLI
Salesforce CLI

After that , now i  perform the following command for creating scratch org and its working as expected.
Again Thanks all.
git clone https://github.com/forcedotcom/sfdx-simple.git
cd sfdx-simple
sfdx force:auth:web:login -d -a "Hub Org"
sfdx force:config:set defaultdevhubusername=sunildevhub@gmail.com
sfdx force:org:create -s -f config/project-scratch-def.json


![image](https://user-images.githubusercontent.com/28707459/50371654-2bae3e80-05e5-11e9-8de7-f731cc078dde.png)

**Comment by rbergman** [comment]
Great!

**Comment by ShekarMS** [comment]
I was getting the same error and below command to install the dx from command line has done the trick..
sfdx plugins:install salesforcedx

Thank you :)
